# This is a basic workflow to help you get started with Actions

name: Daily Stock Check

# Controls when the action will run. 
on:
  schedule:
    - cron: '50 10 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  execute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v4
      - name: Check if Poetry is correctly installed
        run: poetry --version
      - name: Install dependencies
        run: poetry install
      - name: Decrypt secret files
        run: ./secrets/decrypt_secret.sh
        env:
          FIRESTORE_PASSPHRASE: ${{ secrets.FIRESTORE_PASSPHRASE }}
      - name: Run the job
        run: poetry run python main.py
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
